name: Sparkle Note Production CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  BACKEND_REPO: ${{ secrets.ECR_REPOSITORY_BACKEND }}
  FRONTEND_REPO: ${{ secrets.ECR_REPOSITORY_FRONTEND }}

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.meta.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate Image Tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Backend Image
        run: |
          docker build \
          -t backend:${{ steps.meta.outputs.tag }} \
          -f artifacts/api-server/Dockerfile .

      - name: Build Frontend Image
        run: |
          docker build \
          -t frontend:${{ steps.meta.outputs.tag }} \
          -f artifacts/sparkle-note-hub/Dockerfile .

      - name: Save Backend Image
        run: |
          docker save backend:${{ steps.meta.outputs.tag }} \
          -o backend.tar

      - name: Save Frontend Image
        run: |
          docker save frontend:${{ steps.meta.outputs.tag }} \
          -o frontend.tar

      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-image
          path: backend.tar

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-image
          path: frontend.tar

  image-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Backend Image
        uses: actions/download-artifact@v4
        with:
          name: backend-image

      - name: Download Frontend Image
        uses: actions/download-artifact@v4
        with:
          name: frontend-image

      - name: Load Backend Image
        run: docker load -i backend.tar

      - name: Load Frontend Image
        run: docker load -i frontend.tar

        ##Add a debug step
      - name: Find picomatch version
        run: |
          docker run --rm backend:${{ needs.build.outputs.tag }} \
          sh -c "find /app -name package.json | xargs grep -H 'picomatch' || true"

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: backend:${{ needs.build.outputs.tag }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: frontend:${{ needs.build.outputs.tag }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

  push:
    runs-on: ubuntu-latest
    needs:
      - build
      - image-scan

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-image

      - uses: actions/download-artifact@v4
        with:
          name: frontend-image

      - run: docker load -i backend.tar

      - run: docker load -i frontend.tar

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Backend Image
        run: |
          docker tag backend:${{ needs.build.outputs.tag }} \
          $BACKEND_REPO:${{ needs.build.outputs.tag }}

          docker push \
          $BACKEND_REPO:${{ needs.build.outputs.tag }}

      - name: Push Frontend Image
        run: |
          docker tag frontend:${{ needs.build.outputs.tag }} \
          $FRONTEND_REPO:${{ needs.build.outputs.tag }}

          docker push \
          $FRONTEND_REPO:${{ needs.build.outputs.tag }}

  gitops:
    runs-on: ubuntu-latest
    needs:
      - build
      - push

    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: mrutyunjayma/sparkle-note-gitops
          token: ${{ secrets.GH_PAT }}
          path: gitops

      - name: Update Kubernetes Manifests
        run: |
          TAG=${{ needs.build.outputs.tag }}

          cd gitops

          sed -i "s|image:.*backend.*|image: $BACKEND_REPO:$TAG|" apps/backend/deployment.yaml
          sed -i "s|image:.*frontend.*|image: $FRONTEND_REPO:$TAG|" apps/frontend/deployment.yaml

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "Update images to $TAG" || echo "No changes"

          git push

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - image-scan
      - push
      - gitops
    if: always()

    steps:
    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "🚀 CD Pipeline: ${{ job.status }} | Branch: ${{ github.ref_name }} | Commit: ${{ github.sha }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}